import org.gradle.jvm.JvmLibrary
import org.gradle.api.artifacts.result.ResolvedArtifactResult
import org.gradle.api.services.BuildService
import org.gradle.api.services.BuildServiceParameters
import org.gradle.language.base.artifact.SourcesArtifact
import org.gradle.api.file.DuplicatesStrategy

plugins {
    id("dev.architectury.loom") version "1.13-SNAPSHOT" apply false
    id("architectury-plugin") version "3.4-SNAPSHOT"
    id("com.gradleup.shadow") version "8.3.6" apply false
    kotlin("jvm") version "2.2.21" apply false
}

/**
 * Architectury's TransformingTask writes transformer settings (including
 * architectury.srg.mappings) into JVM system properties for the duration of the task.
 * In a multi-Minecraft-version workspace those tasks must not run concurrently, or one
 * version can observe another version's mapping path (e.g. common-1.19.2 reading 1.21.1
 * mappings-srg.tiny and failing with NoSuchFileException).
 *
 * Two layers of serialization:
 * 1) BuildService maxParallelUsages=1 (resource lock while a transform runs)
 * 2) mustRunAfter chain after project evaluation (stable total order in the task graph)
 */
abstract class ArchitecturyTransformMutex : BuildService<BuildServiceParameters.None>

val architecturyTransformMutex = gradle.sharedServices.registerIfAbsent(
    "architecturyTransformMutex",
    ArchitecturyTransformMutex::class.java,
) {
    maxParallelUsages.set(1)
}

allprojects {
    group = project.property("maven_group").toString()
    version = project.property("mod_version").toString()
}

gradle.projectsEvaluated {
    val transformTasks = subprojects
        .flatMap { subproject ->
            subproject.tasks.matching { it.name.startsWith("transformProduction") }
        }
        .sortedBy { it.path }

    for (index in 1 until transformTasks.size) {
        transformTasks[index].mustRunAfter(transformTasks[index - 1])
    }
}

subprojects {
    apply(plugin = "dev.architectury.loom")
    apply(plugin = "architectury-plugin")
    apply(plugin = "maven-publish")
    apply(plugin = "org.jetbrains.kotlin.jvm")

    // Serialize Architectury production transforms across all versioned subprojects.
    tasks.configureEach {
        if (name.startsWith("transformProduction")) {
            usesService(architecturyTransformMutex)
        }
    }

    extensions.configure<BasePluginExtension> {
        archivesName.set("${rootProject.property("archives_name")}-${project.name}")
    }

    repositories {
        mavenCentral()
        maven {
            name = "NeoForged"
            url = uri("https://maven.neoforged.net/releases")
        }
        maven {
            name = "Fuzs Mod Resources"
            url = uri("https://raw.githubusercontent.com/Fuzss/modresources/main/maven/")
        }
    }

    configure<net.fabricmc.loom.api.LoomGradleExtensionAPI> {
        silentMojangMappingsLicense()
    }

    configure<JavaPluginExtension> {
        withSourcesJar()
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    tasks.withType<JavaCompile> {
        options.release.set(21)
    }

    tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21)
        }
    }

    // Some shared source sets intentionally overlap between versioned modules.
    // Ensure jars (especially sourcesJar) remain buildable even if the same source file
    // is contributed from multiple roots.
    tasks.withType<Jar>().configureEach {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }

    // Architectury Transformer sometimes attempts to write debug logs into
    // <project>/.gradle/.architectury-transformer/ without ensuring the directory exists.
    // This can fail on Windows with FileNotFoundException.
    project.file(".gradle/.architectury-transformer").mkdirs()

    tasks.register<Copy>("unpackSources") {
        group = "development"
        description = "Unpacks the sources generated by the decompiler task."

        val decompileTask = tasks.withType<Task>()
            .find { it.name.startsWith("genSourcesWith") }
            ?: tasks.findByName("genSources")

        if (decompileTask != null) {
            dependsOn(decompileTask)

            inputs.files(decompileTask.outputs.files)

            doFirst {
                val files = decompileTask.outputs.files.files
                println(">>> [unpackSources] Found source files in task '${decompileTask.name}':")
                files.forEach { println("    - ${it.absolutePath}") }

                if (files.isEmpty()) {
                    println(">>> [WARNING] No output files found for task '${decompileTask.name}'!")
                }
            }

            val sourceTrees = provider {
                decompileTask.outputs.files
                    .filter { it.name.endsWith(".jar") }
                    .map { zipTree(it) }
            }

            from(sourceTrees) {
                exclude("META-INF/**", "assets/**", "data/**", "*.json", "*.png", "*.class")
            }
        } else {
            enabled = false
        }

        into(layout.buildDirectory.dir("minecraft-sources"))
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
    }

    configure<PublishingExtension> {
        publications {
            create<MavenPublication>("mavenJava") {
                artifactId = extensions.getByType<BasePluginExtension>().archivesName.get()
                from(components["java"])
            }
        }
    }
}